# Use lightweight Python image
FROM python:3.10-slim

# Install system dependencies (INCLUDING TESSERACT)
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 10000

# Start app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]

RUN pip install torch-scatter torch-sparse torch-cluster torch-spline-conv \
    -f https://data.pyg.org/whl/torch-2.2.2+cpu.html

RUN pip install torch-geometric