export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Dashboard } from "./admin/Dashboard";
export { default as Campaigns } from "./admin/campaigns/Campaigns";
export { default as CampaignBuilder } from "./admin/campaigns/CampaignBuilder";
export { default as EmployeeManagement } from "./admin/employees/EmployeeManagement";
export { default as Analytics } from "./admin/Analytics";
export { default as URLScanner } from "./URLScanner";
export { default as InsiderThreat } from "./admin/InsiderThreat";
